[profile.default]
script = 'script'
test = 'test'
extra_output = ['storageLayout']
fs_permissions=[{access="read", path="./out"}, {access="read-write", path="./cache"}]
allow_paths = ["../.."]
remappings=[
  'forge-std/=node_modules/forge-std/src/',
  'ds-test/=node_modules/ds-test/src/',
  '@sphinx-labs/contracts/=lib/sphinx/packages/contracts/contracts/foundry',
]

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${RPC_API_KEY}"
optimism_sepolia = "https://opt-sepolia.g.alchemy.com/v2/${RPC_API_KEY}"
arbitrum_sepolia = "https://arb-sepolia.g.alchemy.com/v2/${RPC_API_KEY}"

[profile.no_optimizer]
optimizer = false