[profile.default]
src = 'contracts'
out = 'forge-artifacts'
remappings = [
  '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
  '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
  '@eth-optimism/contracts-bedrock/=node_modules/@eth-optimism/contracts-bedrock',
  'forge-std/=node_modules/forge-std/src/',
  'ds-test/=node_modules/ds-test/src/'
]
gas_price=1